/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 untitled.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/untitled.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.comp_desk_c} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.comp_desk} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.comp_desk_b} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.comp_desk_a} />
      </group>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_10.geometry} material={materials.comp_desk_2remote} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.comp_desk_1remote} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.comp_desk_button} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.comp_desk_remote} />
      </group>
      <mesh geometry={nodes.Object_14.geometry} material={materials.comp_desk_top} />
    </group>
  )
}

useGLTF.preload('/untitled.glb')
