/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 untitled.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/untitled.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        
        <mesh geometry={nodes.Object_4.geometry} material={materials.comp_desk_c}
          material-aoMap={allMaterials[useSelector((state) => state.modelCustomization.items.comp_desk_c.material)].aoMap}
          material-roughnessMap={allMaterials[useSelector((state) => state.modelCustomization.items.comp_desk_c.material)].roughnessMap}
          material-normalMap={allMaterials[useSelector((state) => state.modelCustomization.items.comp_desk_c.material)].normalMap}
          material-map={allMaterials[useSelector((state) => state.modelCustomization.items.comp_desk_c.material)].baseColorMap}
          material-metalnessMap={allMaterials[useSelector((state) => state.modelCustomization.items.comp_desk_c.material)].metalnessMap}
          material-metalness={allMaterials[useSelector((state) => state.modelCustomization.items.comp_desk_c.material)].metalness}
        />
      
        
        <mesh geometry={nodes.Object_5.geometry} material={materials.comp_desk}
          material-aoMap={allMaterials[useSelector((state) => state.modelCustomization.items.comp_desk.material)].aoMap}
          material-roughnessMap={allMaterials[useSelector((state) => state.modelCustomization.items.comp_desk.material)].roughnessMap}
          material-normalMap={allMaterials[useSelector((state) => state.modelCustomization.items.comp_desk.material)].normalMap}
          material-map={allMaterials[useSelector((state) => state.modelCustomization.items.comp_desk.material)].baseColorMap}
          material-metalnessMap={allMaterials[useSelector((state) => state.modelCustomization.items.comp_desk.material)].metalnessMap}
          material-metalness={allMaterials[useSelector((state) => state.modelCustomization.items.comp_desk.material)].metalness}
        />
      
        
        <mesh geometry={nodes.Object_6.geometry} material={materials.comp_desk_b}
          material-aoMap={allMaterials[useSelector((state) => state.modelCustomization.items.comp_desk_b.material)].aoMap}
          material-roughnessMap={allMaterials[useSelector((state) => state.modelCustomization.items.comp_desk_b.material)].roughnessMap}
          material-normalMap={allMaterials[useSelector((state) => state.modelCustomization.items.comp_desk_b.material)].normalMap}
          material-map={allMaterials[useSelector((state) => state.modelCustomization.items.comp_desk_b.material)].baseColorMap}
          material-metalnessMap={allMaterials[useSelector((state) => state.modelCustomization.items.comp_desk_b.material)].metalnessMap}
          material-metalness={allMaterials[useSelector((state) => state.modelCustomization.items.comp_desk_b.material)].metalness}
        />
      
        
        <mesh geometry={nodes.Object_7.geometry} material={materials.comp_desk_a}
          material-aoMap={allMaterials[useSelector((state) => state.modelCustomization.items.comp_desk_a.material)].aoMap}
          material-roughnessMap={allMaterials[useSelector((state) => state.modelCustomization.items.comp_desk_a.material)].roughnessMap}
          material-normalMap={allMaterials[useSelector((state) => state.modelCustomization.items.comp_desk_a.material)].normalMap}
          material-map={allMaterials[useSelector((state) => state.modelCustomization.items.comp_desk_a.material)].baseColorMap}
          material-metalnessMap={allMaterials[useSelector((state) => state.modelCustomization.items.comp_desk_a.material)].metalnessMap}
          material-metalness={allMaterials[useSelector((state) => state.modelCustomization.items.comp_desk_a.material)].metalness}
        />
      
      </group>
      <group rotation={[Math.PI / 2, 0, 0]}>
        
        <mesh geometry={nodes.Object_10.geometry} material={materials.comp_desk_2remote}
          material-aoMap={allMaterials[useSelector((state) => state.modelCustomization.items.comp_desk_2remote.material)].aoMap}
          material-roughnessMap={allMaterials[useSelector((state) => state.modelCustomization.items.comp_desk_2remote.material)].roughnessMap}
          material-normalMap={allMaterials[useSelector((state) => state.modelCustomization.items.comp_desk_2remote.material)].normalMap}
          material-map={allMaterials[useSelector((state) => state.modelCustomization.items.comp_desk_2remote.material)].baseColorMap}
          material-metalnessMap={allMaterials[useSelector((state) => state.modelCustomization.items.comp_desk_2remote.material)].metalnessMap}
          material-metalness={allMaterials[useSelector((state) => state.modelCustomization.items.comp_desk_2remote.material)].metalness}
        />
      
        
        <mesh geometry={nodes.Object_11.geometry} material={materials.comp_desk_1remote}
          material-aoMap={allMaterials[useSelector((state) => state.modelCustomization.items.comp_desk_1remote.material)].aoMap}
          material-roughnessMap={allMaterials[useSelector((state) => state.modelCustomization.items.comp_desk_1remote.material)].roughnessMap}
          material-normalMap={allMaterials[useSelector((state) => state.modelCustomization.items.comp_desk_1remote.material)].normalMap}
          material-map={allMaterials[useSelector((state) => state.modelCustomization.items.comp_desk_1remote.material)].baseColorMap}
          material-metalnessMap={allMaterials[useSelector((state) => state.modelCustomization.items.comp_desk_1remote.material)].metalnessMap}
          material-metalness={allMaterials[useSelector((state) => state.modelCustomization.items.comp_desk_1remote.material)].metalness}
        />
      
        
        <mesh geometry={nodes.Object_12.geometry} material={materials.comp_desk_button}
          material-aoMap={allMaterials[useSelector((state) => state.modelCustomization.items.comp_desk_button.material)].aoMap}
          material-roughnessMap={allMaterials[useSelector((state) => state.modelCustomization.items.comp_desk_button.material)].roughnessMap}
          material-normalMap={allMaterials[useSelector((state) => state.modelCustomization.items.comp_desk_button.material)].normalMap}
          material-map={allMaterials[useSelector((state) => state.modelCustomization.items.comp_desk_button.material)].baseColorMap}
          material-metalnessMap={allMaterials[useSelector((state) => state.modelCustomization.items.comp_desk_button.material)].metalnessMap}
          material-metalness={allMaterials[useSelector((state) => state.modelCustomization.items.comp_desk_button.material)].metalness}
        />
      
        
        <mesh geometry={nodes.Object_9.geometry} material={materials.comp_desk_remote}
          material-aoMap={allMaterials[useSelector((state) => state.modelCustomization.items.comp_desk_remote.material)].aoMap}
          material-roughnessMap={allMaterials[useSelector((state) => state.modelCustomization.items.comp_desk_remote.material)].roughnessMap}
          material-normalMap={allMaterials[useSelector((state) => state.modelCustomization.items.comp_desk_remote.material)].normalMap}
          material-map={allMaterials[useSelector((state) => state.modelCustomization.items.comp_desk_remote.material)].baseColorMap}
          material-metalnessMap={allMaterials[useSelector((state) => state.modelCustomization.items.comp_desk_remote.material)].metalnessMap}
          material-metalness={allMaterials[useSelector((state) => state.modelCustomization.items.comp_desk_remote.material)].metalness}
        />
      
      </group>
      
        <mesh geometry={nodes.Object_14.geometry} material={materials.comp_desk_top}
          material-aoMap={allMaterials[useSelector((state) => state.modelCustomization.items.comp_desk_top.material)].aoMap}
          material-roughnessMap={allMaterials[useSelector((state) => state.modelCustomization.items.comp_desk_top.material)].roughnessMap}
          material-normalMap={allMaterials[useSelector((state) => state.modelCustomization.items.comp_desk_top.material)].normalMap}
          material-map={allMaterials[useSelector((state) => state.modelCustomization.items.comp_desk_top.material)].baseColorMap}
          material-metalnessMap={allMaterials[useSelector((state) => state.modelCustomization.items.comp_desk_top.material)].metalnessMap}
          material-metalness={allMaterials[useSelector((state) => state.modelCustomization.items.comp_desk_top.material)].metalness}
        />
      
    </group>
  )
}

useGLTF.preload('/untitled.glb')
